# Generated by Django 4.2.2 on 2025-12-03 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tapnote", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(max_length=100)),
                ("work_id", models.CharField(max_length=100)),
                ("chapter_id", models.CharField(max_length=100)),
                ("para_index", models.IntegerField()),
                ("content", models.TextField()),
                ("user_name", models.CharField(default="匿名", max_length=100)),
                ("user_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user_avatar",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("context_text", models.TextField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("likes", models.IntegerField(default=0)),
            ],
        ),
    ]
