# Generated by Django 4.2.2 on 2025-12-03 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tapnote", "0002_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="LikeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=100, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="like_records",
                        to="tapnote.comment",
                    ),
                ),
            ],
            options={
                "unique_together": {("comment", "ip"), ("comment", "user_id")},
            },
        ),
    ]
