# Generated by Django 4.2.2 on 2025-12-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tapnote", "0005_note_link_target"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="link_target",
            field=models.CharField(
                choices=[("_blank", "New Tab"), ("_self", "Same Tab")],
                default="_self",
                max_length=10,
            ),
        ),
    ]
