# Generated by Django 4.2.2 on 2025-12-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tapnote", "0006_alter_note_link_target"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(max_length=100)),
                ("user_id", models.CharField(max_length=100)),
                ("reason", models.TextField(blank=True, null=True)),
                ("banned_by", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("site_id", "user_id")},
            },
        ),
    ]
